name: Build and Test APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          flutter pub get
          flutter gen-l10n

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload Test APKs
        uses: actions/upload-artifact@v7
        with:
          name: Test-APKs
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
